dataset:
    name: &dataset_name 'imagenet'
    root: &data_dir './resource/data/ILSVRC2012/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'test.txt']
    normalizer:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

input_shape: [3, 224, 224]

model:
    type: &model_type 'mobilenet_v2'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    pretrained: True
    ckpt: !join ['./resource/ckpt/', *experiment, '.ckpt']
    params:
        num_classes: 1000
        # Default parameters for input size(3, 224, 224)

train:
    epoch: 200
    batch_size: 20
    rough_size: 256
    interval: -1
    optimizer:
        type: 'SGD'
        params:
            lr: 0.001
            momentum: 0.9
            weight_decay: 0.0005
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [100, 200]
            gamma: 0.1
    criterion:
        type: 'CrossEntropyLoss'
        params:
            reduction: 'mean'

test:
    batch_size: 1
    jquality: 0
    compression:
        type:
        size:
